name: Build Mod Jar

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ "master" ]  # 替换为你的实际分支名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码（必须优先执行）
      - uses: actions/checkout@v4
        with:
         validate-wrappers: false  # 关闭验证

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 设置 Gradle（可选，但推荐）
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. 修复 gradlew 权限（关键修复！）
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 5. 执行构建
      - name: Build
        run: ./gradlew build

      # 6. 上传生成的 Jar 文件
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Jar
          path: build/libs/*.jar
